// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Bookshelf.DATA.Models;

public partial class Book
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(50)]
    [Unicode(false)]
    public string Name { get; set; }

    [Required]
    [Column("author")]
    [StringLength(100)]
    [Unicode(false)]
    public string Author { get; set; }

    [Column("publisher")]
    [StringLength(50)]
    [Unicode(false)]
    public string Publisher { get; set; }

    [InverseProperty("IdBooksNavigation")]
    public virtual ICollection<Loan> Loans { get; set; } = new List<Loan>();
}