// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Bookshelf.DATA.Models;

[Table("Customer")]
public partial class Customer
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Required]
    [Column("name")]
    [StringLength(100)]
    [Unicode(false)]
    public string Name { get; set; }

    [Required]
    [Column("adress")]
    [StringLength(50)]
    [Unicode(false)]
    public string Adress { get; set; }

    [Required]
    [Column("city")]
    [StringLength(50)]
    [Unicode(false)]
    public string City { get; set; }

    [Required]
    [Column("district")]
    [StringLength(50)]
    [Unicode(false)]
    public string District { get; set; }

    [InverseProperty("IdCustomerNavigation")]
    public virtual ICollection<Loan> Loans { get; set; } = new List<Loan>();
}