// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace Bookshelf.DATA.Models;

[Table("Loan")]
public partial class Loan
{
    [Key]
    [Column("id")]
    public int Id { get; set; }

    [Column("idBooks")]
    public int IdBooks { get; set; }

    [Column("idCustomer")]
    public int IdCustomer { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DateLoan { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DateReturn { get; set; }

    [ForeignKey("IdBooks")]
    [InverseProperty("Loans")]
    public virtual Book IdBooksNavigation { get; set; }

    [ForeignKey("IdCustomer")]
    [InverseProperty("Loans")]
    public virtual Customer IdCustomerNavigation { get; set; }
}